### ISSUE TITLE
An issue in the MISI implementation

### ISSUE THREAD

**Issue by Emrys365** [magronp/omisi#1]
Hi, thank you for sharing your implementation of the MISI algorithms!

However, I was confused by the following line in the `misi` implementation:
https://github.com/magronp/omisi/blob/master/source/algorithms.py#L58

According to the [original MISI algorithm](https://ieeexplore.ieee.org/abstract/document/5409531), after each iteration, the (input) target magnitude should be used as the magnitude of the refined spectrum.

In the aforementioned code, however, it seems to also change the phase by multiplying with the target phase. Is this intentionally designed so?

> BTW, After modifying it with the following code (to match the original MISI algorithm):
> ```python
>         stft_estim = corrected_stft * np.abs(spectrograms_target) / (np.abs(corrected_stft) + sys.float_info.epsilon)
> ```
> I observed a large improvement in the SDR score.

**Comment by magronp** [comment]
Hi,
Thanks a lot for your interest in this code.
I'm not sure I understand your question though: when using the code in my experiments, "spectrogram_target" is the spectrogram, meaning it's nonnegative: there is no phase change.
In other words, np.abs(spectrogram_target) = spectrogram_target.
If for some reason you use a complex-valued "spectrogram_target", then of course you need to take the abs of it.
Best,
Paul

**Comment by Emrys365** [comment]
Oh I see your point. I misunderstood that it is an STFT spectrum too, and that's why I thought the code may unexpectedly change the phase.

Thanks a lot for your clarification, Paul!

Best,
Wangyou
